server.port: 10120

solon.app:
  namespace: herz
  group: demo
  name: aic


# 参数 org.lealone.db.ConnectionSetting

lealone.db1:
  # 嵌入式 jdbc:lealone:embed:lealone?user=root
  # 数据库 jdbc:lealone:tcp://localhost:9210/lealone?user=root
  #
  jdbcUrl: jdbc:lealone:tcp://localhost:9210/lealone?user=root